[workspace]
members = [
    "fs",
    ".",
]
default-members = [
    "fs",
    "."
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.66" # Due to strict encoding library (caused by GAD)
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.0.0"
baid58 = "0.3.1"
strict_encoding = "2.1.1"
strict_types = "1.1.0"
rgb-std = { version = "0.10.0", features = ["fs"] }
rgb-wallet = { version = "0.10.0", features = ["fs"] }

[package]
name = "rgb-contracts"
version = "0.10.0"
description = " RGB: scalable & confidential smart contracts for Bitcoin & Lightning network"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "std"]

[lib]
name = "rgb"

[[bin]]
name = "rgb"
required-features = ["cli"]

[dependencies]
amplify = { workspace = true }
baid58 = { workspace = true }
strict_types = { workspace = true, features = ["serde"] }
commit_verify = "0.10.0"
bp-core = { version = "0.10.1", features = ["serde"] }
rgb-std = { workspace = true }
rgb-wallet = { workspace = true }
rgb-persist-fs = { version = "0.10.0", path = "fs" }
bitcoin = { version = "0.30.0", features = ["serde"] }
electrum-client = { git = "https://github.com/RCasatta/rust-electrum-client", branch = "bitcoin_0_30", version = "0.13.0", optional = true }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"], optional = true }
env_logger = "0.10.0"
clap = { version = "4.1.8", features = ["derive", "env"], optional = true }
shellexpand = { version = "3.0.0", optional = true }
serde = "1.0.159"
serde_yaml = "0.9.19"

[features]
default = ["electrum", "log"]
all = ["cli", "log"]
electrum = ["electrum-client", "log"]
cli = ["clap", "shellexpand", "log", "electrum"]

[package.metadata.docs.rs]
features = [ "all" ]


[patch.crates-io]
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "commit_encode_derive" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-primitives = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "commit_derive" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "fix/op-conceal" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "rgb20" }
